// <auto-generated />
using System;
using CdcBridge.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CdcBridge.Worker.Migrations
{
    [DbContext(typeof(CdcBridgeDbContext))]
    [Migration("20251005211751_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("CdcBridge.Persistence.Models.BufferedChangeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BufferedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Change")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RowLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingInstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BufferedChangeEvents");
                });

            modelBuilder.Entity("CdcBridge.Persistence.Models.ReceiverDeliveryStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BufferedChangeEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BufferedChangeEventId", "ReceiverName")
                        .IsUnique();

                    b.ToTable("ReceiverDeliveryStatuses");
                });

            modelBuilder.Entity("CdcBridge.Persistence.Models.TrackingInstanceState", b =>
                {
                    b.Property<string>("TrackingInstanceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastProcessedRowLabel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("TrackingInstanceName");

                    b.ToTable("TrackingInstanceStates");
                });

            modelBuilder.Entity("CdcBridge.Persistence.Models.ReceiverDeliveryStatus", b =>
                {
                    b.HasOne("CdcBridge.Persistence.Models.BufferedChangeEvent", "BufferedChangeEvent")
                        .WithMany("DeliveryStatuses")
                        .HasForeignKey("BufferedChangeEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BufferedChangeEvent");
                });

            modelBuilder.Entity("CdcBridge.Persistence.Models.BufferedChangeEvent", b =>
                {
                    b.Navigation("DeliveryStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
