$schema: ./settings.schema.json
# Формат настроек для трекинга изменений в таблицах

connections:
  - # Объект с настройками подключения к источнику данных (БД)
    name: shop_application_db
    description: Подключение к базе данных приложения для покупок
    type: SqlServer
    connectionString: Server=localhost;Database=shop;User Id=sa;Password=your_password;
    active: true

trackingInstances:
  - # Объект с настройками трекинга изменений в таблице
    sourceTable: users
    capturedColumns:
      - name
      - email
      - status
    description: Захват основных изменений в таблице пользователей
    connection: shop_application_db
    active: true
    checkIntervalInSeconds: 20
    name: usersTracking

filters:
  - # Примеры фильтров для трекинга изменений (Привязаны к trackingInstance)
    description: Фильтр для отслеживания только изменений статуса пользователя с active на inactive
    name: ActiveToInactive
    trackingInstance: usersTracking
    type: JsonPathFilter
    parameters:
      expression: $[?(@.data.old.status == 'active' && @.data.new.status == 'inactive')]

  - description: Фильтр для отслеживания удаленных пользователей
    name: DeletedUsers
    trackingInstance: usersTracking
    type: JsonPathFilter
    parameters:
      expression: $[?(@.eventType == 'Delete')]

transformers:
  - # Примеры трансформеров для преобразования данных перед отправкой получателям
    name: AnalyticsServiceTransformer
    description: Преобразователь для отправки данных в аналитический сервис
    trackingInstance: usersTracking
    type: JSONataTransformer
    parameters:
      transformation: >-
        { 'userId': data.new.id, 'displayName': data.new.name, 'login': data.new.email, 'isActive': data.new.status = 'active', 'timeStamp': createdAt }

receivers:
  - retryCount: 3
    name: AnalyticsWebHook
    # Примеры получателей для отправки уведомлений об изменениях
    description: Получатель для отправки уведомлений на WebHook в сервис аналитики
    filter: ActiveToInactive
    transformer: AnalyticsServiceTransformer
    trackingInstance: usersTracking
    type: WebhookReceiver
    parameters:
      useWindowsAuth: false
      webhookUrl: https://hooks.analytics.com/services/your/webhook/url
      httpMethod: POST
      headers:
        Authorization: Bearer 49aQVmpt3GpGGq8PqzT2MGEJGHMdDrDoQ5u9moADuh7oKdhsSSfxOpOvymfkH7GD
        Content-Type: application/json
        User-Agent: ChangeTracker/1.0
        Accept: application/json